apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployspringboot
spec:
  replicas: 1
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      hostNetwork: true
      containers:
      - name: my-web
        #image: spring
        image: durgesh13511/springpro:4.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicespringboot
  labels:
    app: springapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort : 30009
  selector:
    app: springapp
